### ISSUE TITLE
Define pyproject.toml and make this python package releasable...

### ISSUE THREAD

**Issue by TNO-SlaFleur** [flexiblepower/s2-python#12]
by integrating twine and other steps of the Python release protocol: https://packaging.python.org/en/latest/tutorials/packaging-projects/

**Comment by TNO-SlaFleur** [comment]
That would be great Victor, thanks! I think it is fine to start with setup.py if that is already available, but it might be good to migrate to pyproject.toml somewhere in the future as that is the new standard. Shall we make a separate ticket for that and change this one to using setup.py? Does that have your preference?

**Comment by victorgarcia98** [comment]
Great! 

Probably we want to use pyproject.toml, directly, I'll take a look. Probably there not as many differences.

**Comment by TNO-SlaFleur** [comment]
#14 has added the necessary files to make a distributable.
