### ISSUE TITLE
add GitHub action for publishing to PyPI and testing

### ISSUE THREAD

**Issue by victorgarcia98** [flexiblepower/s2-python#18]
In the past, I adapted a GH pipeline that we had for the `flexmeasures-client` for the `s2-ws-json-python` .

The pipeline does the following:
- linting
- testing
- publishing: when pushing a new tag with a version format

I'll create a PR soon to get closer to the [first release](https://github.com/flexiblepower/s2-ws-json-python/issues/17).

**Comment by TNO-SlaFleur** [comment]
Looking forward to the PR!

**Comment by TNO-SlaFleur** [comment]
Done with https://github.com/flexiblepower/s2-python/pull/27
