### ISSUE TITLE
Rerename from s2-python

### ISSUE THREAD

**Issue by lfse-slafleur** [flexiblepower/s2-python#26]
@victorgarcia98 

I notified some of my colleagues of our chosen rename and got some push-back. Their view is that having different implementations of S2 in other protocols than websockets+json is realistic for the future. So we do have to add that to the name before we release.

The first name was s2-ws-json-python. I agree that having a simpler name is more preferable but having both websockets & json in the identifier is given to me as a requirement. Would the previous name s2-ws-json-python (with `import s2wsjson`) suit your needs?

**Comment by victorgarcia98** [comment]
Sure, if it's a requirement it's ok for me to apply the rerename.

I'm wondering how a different implementation of S2 would look like in practice. Let's say you want to communicate XML, we could transform the XML into a dict using [xmltodict](https://github.com/martinblech/xmltodict) and apply the current classes. So in that case, It would be adding two new methods to the mixin (from_xml, to_xml).

Regarding the communication protocol, let's say HTTP, I guess that one approach would be to use polling to handle bidirectional communication. In that case, the schema should be the same as in websockets, right?

**Comment by TNO-SlaFleur** [comment]
Thanks for raising a very valid point. The schema remains the same regardless of communication protocols which is why we renamed it in the first place. I did not raise this during our internal discussions. I am going to restart the discussion internally as I would really like to not change the name for many reasons, including the one you are raising.

**Comment by lfse-slafleur** [comment]
Closing this issue as current time seems to be accepted.
